# helloworld-zig0.11 on Hyperlight
#
# just build        - Build rootfs via kraft build
# just run          - Run application (uses Hyperlight runtime)
# just clean        - Remove build artifacts

initrd := ".unikraft/build/initramfs-x86_64.cpio"
memory := "64Mi"

# Build rootfs via kraft
build:
	kraft build --rootfs ./Dockerfile --plat hyperlight --arch x86_64

# Run application with Kraft
run:
	kraft run --plat hyperlight --rm --memory {{memory}} --rootfs {{initrd}} .

# Clean build artifacts
[unix]
clean:
	rm -rf .unikraft .config.*
