services:
  redis:
    image: redis:7.2
    ports:
      - '6379:6379'
    networks:
      internal:
        ipv4_address: 172.23.0.2
    mem_reservation: 512M

  web1:
    build: ./web
    hostname: web1
    ports:
      - '81:5000'
    networks:
      internal:
        ipv4_address: 172.23.0.3
    mem_reservation: 512M
    depends_on:
      - redis

  web2:
    build: ./web
    hostname: web2
    ports:
      - '82:5000'
    networks:
      internal:
        ipv4_address: 172.23.0.4
    mem_reservation: 512M
    depends_on:
      - redis

  nginx:
    image: nginx:1.25
    ports:
    - '8080:80'
    volumes:
      - ./nginx:/etc/nginx
    depends_on:
    - web1
    - web2
    networks:
      internal:

networks:
  internal:
    ipam:
      config:
        - subnet: 172.23.0.1/16

