name: library/httpbingo:2.13.4

on:
  repository_dispatch:
    types: [core_merge]

  workflow_dispatch:

  schedule:
  - cron: '30 0 * * *'

  push:
    branches: [main]
    paths:
    - 'library/httpbingo/2.13.4/**'
    - '.github/workflows/library-httpbingo2.13.4.yaml'
    - '!library/httpbingo/2.13.4/README.md'

  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]
    paths:
    - 'library/httpbingo/2.13.4/**'
    - '.github/workflows/library-httpbingo2.13.4.yaml'
    - '!library/httpbingo/2.13.4/README.md'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
        - plat: qemu
          arch: x86_64
        - plat: fc
          arch: x86_64

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build httpbingo2.13.4
      uses: unikraft/kraftkit@staging
      with:
        loglevel: debug
        workdir: library/httpbingo/2.13.4
        runtimedir: /github/workspace/.kraftkit
        plat: ${{ matrix.plat }}
        arch: ${{ matrix.arch }}
        push: false
        output: oci://index.unikraft.io/unikraft.org/httpbingo:2.13.4

    - name: Archive OCI digests
      uses: actions/upload-artifact@v4
      with:
        name: oci-digests-${{ matrix.arch }}-${{ matrix.plat }}
        path: ${{ github.workspace }}/.kraftkit/oci/digests
        if-no-files-found: error

  push:
    if: ${{ github.event_name == 'push' || github.event_name == 'schedule' }}
    needs: [ build ]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login to OCI registry
      uses: docker/login-action@v3
      with:
        registry: index.unikraft.io
        username: ${{ secrets.REG_USERNAME }}
        password: ${{ secrets.REG_TOKEN }}

    - name: Retrieve, merge and push OCI digests
      uses: ./.github/actions/merge-oci-digests
      with:
        name: index.unikraft.io/unikraft.org/httpbingo:2.13.4
        push: true


  run-remote:
    name: Test httpbingo:2.13.4 (Remote OCI)
    needs: [build, push]
    runs-on: ubuntu-latest
    steps:
      - name: Login to OCI registry
        uses: docker/login-action@v3
        with:
          registry: index.unikraft.io
          username: ${{ secrets.REG_USERNAME }}
          password: ${{ secrets.REG_TOKEN }}

      - name: Pull, run, validate and cleanup unikernel
        run: |
          set -euo pipefail
          echo "Pull and start httpbingo:2.13.4 unikernel"
          IMAGE=index.unikraft.io/unikraft.org/httpbingo:2.13.4
          docker pull "$IMAGE"
          CONTAINER_ID=$(docker run --rm -d "$IMAGE")
          echo "Wait and validate container startup"
          sleep 5
          if ! docker ps --filter "id=$CONTAINER_ID" --format '{{.ID}}' | grep -q .; then
            echo "ERROR: httpbingo:2.13.4 unikernel is not running" >&2
            docker logs "$CONTAINER_ID" >&2 || true
            docker stop "$CONTAINER_ID" || true
            exit 1
          fi
          echo "httpbingo:2.13.4 unikernel started successfully"
          echo "Cleanup container"
          docker stop "$CONTAINER_ID" || true
      
  run-local:
    name: Test httpbingo:2.13.4 (Local build)
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install kraft CLI
        run: |
          echo "deb [trusted=yes] https://deb.pkg.kraftkit.sh/ /" | sudo tee /etc/apt/sources.list.d/kraftkit.list
          sudo apt-get update
          sudo apt-get install -y kraftkit
      - name: Build, run and validate unikernel
        run: |
          set -euo pipefail
          sudo chmod 666 /dev/kvm
          cd library/httpbingo/2.13.4
          echo "Build httpbingo:2.13.4 unikernel"
          kraft build --no-cache --no-update --plat qemu --arch x86_64
  
          echo "Run httpbingo:2.13.4 unikernel"
          kraft run --rm -M 256M --plat qemu --arch x86_64 . &
          PID=$!
          sleep 5

          echo "httpbingo:2.13.4 unikernel started successfully locally"

          echo "Cleanup httpbingo:2.13.4 unikernel"
          sudo kill "$PID" || true