name: library/node:18

on:
  repository_dispatch:
    types: [core_merge, elfloader_merge, libelf_merge, lwip_merge]

  workflow_dispatch:

  schedule:
    - cron: '0 0 * * *' # Everyday at 12AM

  push:
    branches: [main]
    paths:
      - 'library/node/18/**'
      - '.github/workflows/library-node18.yaml'
      - '!library/node/18/README.md'

  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]
    paths:
      - 'library/node/18/**'
      - '.github/workflows/library-node18.yaml'
      - '!library/node/18/README.md'

# Automatically cancel in-progress actions on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - plat: qemu
            arch: x86_64
          - plat: fc
            arch: x86_64

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build node18 for ${{ matrix.plat }}/${{ matrix.arch }}
        uses: unikraft/kraftkit@staging
        with:
          loglevel: debug
          workdir: library/node/18
          runtimedir: /github/workspace/.kraftkit
          plat: ${{ matrix.plat }}
          arch: ${{ matrix.arch }}
          push: false
          output: oci://index.unikraft.io/unikraft.org/node:18

      - name: Archive OCI digests
        uses: actions/upload-artifact@v4
        with:
          name: oci-digests-${{ matrix.arch }}-${{ matrix.plat }}
          path: ${{ github.workspace }}/.kraftkit/oci/digests
          if-no-files-found: error

  run:
    needs: [build]
    strategy:
      fail-fast: false
      matrix:
        include:
          - plat: qemu
            arch: x86_64
          - plat: fc
            arch: x86_64

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install kraft CLI
        run: |
          echo "deb [trusted=yes] https://deb.pkg.kraftkit.sh/ /" | 
          sudo tee /etc/apt/sources.list.d/kraftkit.list
          sudo apt-get update
          sudo apt-get install -y kraftkit

      - name: Build & Run node18 unikernel on ${{ matrix.plat }}/${{ matrix.arch }}
        run: |
          set -euo pipefail
          sudo chmod 666 /dev/kvm
          cd library/node/18

          echo "Re-building unikernel for ${{ matrix.plat }}/${{ matrix.arch }}"
          kraft build --no-cache --no-update \
            --plat ${{ matrix.plat }} --arch ${{ matrix.arch }}

          echo "Running unikernel"
          kraft run --rm -M 512M -p 8080:8080 \
            --plat ${{ matrix.plat }} --arch ${{ matrix.arch }} . &
          PID=$!
          sleep 5

          echo "Waiting for port 8080"
          TIMEOUT=10
          START_TS=$(date +%s)
          until nc -z localhost 8080; do
            if [ $(( $(date +%s) - START_TS )) -ge $TIMEOUT ]]; then
              echo "ERROR: port 8080 did not open within ${TIMEOUT}s" >&2
              sudo kill "$PID" || true
              exit 1
            fi
            sleep 1
          done
          echo "Port 8080 is now accepting connections"

          echo "Validating HTTP response"
          EXPECTED="Hello, world!"
          RESPONSE=$(curl -fs http://localhost:8080/)
          if [ "$RESPONSE" != "$EXPECTED" ]; then
            echo "ERROR: expected '$EXPECTED' but got '$RESPONSE'" >&2
            sudo kill "$PID" || true
            exit 1
          fi
          echo "Response is correct: '$RESPONSE'"

          echo "Cleaning up"
          sudo kill "$PID" || true

  push:
    if: ${{ github.event_name == 'push' || github.event_name == 'schedule' }}
    needs: [run]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to OCI registry
        uses: docker/login-action@v3
        with:
          registry: index.unikraft.io
          username: ${{ secrets.REG_USERNAME }}
          password: ${{ secrets.REG_TOKEN }}

      - name: Retrieve, merge and push OCI digests
        uses: ./.github/actions/merge-oci-digests
        with:
          name: index.unikraft.io/unikraft.org/node:18
          push: true
