name: library/nginx:1.15

on:
  repository_dispatch:
    types: [core_merge, lwip_merge, musl_merge, nginx_merge]

  workflow_dispatch:

  schedule:
  - cron: '0 1 * * *'

  push:
    branches: [main]
    paths:
    - 'library/nginx/1.15/**'
    - '.github/workflows/library-nginx1.15.yaml'

  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]
    paths:
    - 'library/nginx/1.15/**'
    - '.github/workflows/library-nginx1.15.yaml'

# Automatically cancel in-progress actions on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
        - plat: qemu
          arch: x86_64
        - plat: qemu
          arch: arm64
        - plat: fc
          arch: x86_64
        - plat: fc
          arch: arm64

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build nginx1.15
      uses: unikraft/kraftkit@staging
      with:
        loglevel: debug
        workdir: library/nginx/1.15
        runtimedir: /github/workspace/.kraftkit
        plat: ${{ matrix.plat }}
        arch: ${{ matrix.arch }}
        push: false
        output: oci://index.unikraft.io/unikraft.org/nginx:1.15
        after: |
          # GitHub Actions can only executed with QEMU (via emulation mode)
          if [[ ${{ matrix.plat }} != "qemu" ]]; then
            exit 0;
          fi

          export KRAFTKIT_LOG_LEVEL=debug
          export KRAFTKIT_RUNTIME_DIR=/github/workspace/.kraftkit

          set -xe;

          kraft run \
            --detach \
            --disable-acceleration \
            --plat ${{ matrix.plat }} \
            --arch ${{ matrix.arch }} \
            --name nginx-${GITHUB_RUN_ID} \
            --port 8080:80 \
            index.unikraft.io/unikraft.org/nginx:1.15

          function cleanup {
            kraft logs nginx-${GITHUB_RUN_ID} || true;
            kraft rm nginx-${GITHUB_RUN_ID} || true;
          }
          trap cleanup EXIT
          trap cleanup INT

          curl -Lv --fail http://localhost:8080

    - name: Archive OCI digests
      uses: actions/upload-artifact@v4
      with:
        name: oci-digests-${{ matrix.arch }}-${{ matrix.plat }}
        path: ${{ github.workspace }}/.kraftkit/oci/digests
        if-no-files-found: error

  push:
    if: ${{ github.event_name == 'push' || github.event_name == 'schedule' }}
    needs: [ build ]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login to OCI registry
      uses: docker/login-action@v3
      with:
        registry: index.unikraft.io
        username: ${{ secrets.REG_USERNAME }}
        password: ${{ secrets.REG_TOKEN }}

    - name: Retrieve, merge and push OCI digests
      uses: ./.github/actions/merge-oci-digests
      with:
        name: index.unikraft.io/unikraft.org/nginx:1.15
        push: true
